language: go
go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - tip
env:
    ICU_LIB: /usr
sudo: required
before_install:
    - sudo apt-get -q update
    - sudo apt-get -y purge
        libicu-dev
        icu-devtools
    - ./.build/install-icu4c.sh
    - sudo add-apt-repository -y ppa:masterminds/glide
    - sudo apt-get -qq update
    - sudo apt-get -y install glide
    - sudo apt-get -y install
        texlive-latex-base
        texlive-latex-extra
        texlive-fonts-recommended
        texlive-fonts-extra
        texlive-lang-cyrillic
        texlive-luatex
        pandoc
        wkhtmltopdf

# TODO: for some unclear reason tex won't work on Travis.
# I tried use it (via pandoc) with pdflatex and xelatex engines.
# With pdflatex I had troubles with babel, which won't use Russian language setting.
# With xelatex it fails with some strange error (TeX capacity exceeded, sorry
# [input stack size=5000]).
#
#        texlive-latex-base
#        texlive-latex-extra
#        texlive-fonts-recommended
#        texlive-fonts-extra
#        texlive-lang-cyrillic
#        texlive-xetex
#        pandoc
install:
    - glide i
script:
    - make clean test build ace-pdf
#    - make
