language: go
go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - tip
env:
    ICU_LIB: /usr
sudo: required
before_install:
    - sudo apt-get -q update
    - sudo apt-get -y purge
        libicu-dev
        icu-devtools
    - ./.build/install-icu4c.sh
    - sudo add-apt-repository -y ppa:masterminds/glide
    - sudo apt-get -qq update
    - sudo apt-get -y install glide
    - sudo apt-get -y install
        texlive-full
        pandoc
        wkhtmltopdf
install:
    - glide i
script:
    - make
