language: go
go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - tip
sudo: required
before_install:
    - sudo add-apt-repository -y ppa:masterminds/glide
    - sudo apt-get -qq update
    - sudo apt-get -y install glide
install:
    - glide i
script:
    - go build
